### ISSUE TITLE
How does Frappe compare to Sodium?

### ISSUE THREAD

**Issue by jakub-trzebiatowski** [darkstalker/frappe#4]
I've read ["Functional Reactive Programming" book](https://www.amazon.com/Functional-Reactive-Programming-Stephen-Blackheath/dp/1633430103) by Stephen Blackheath and Anthony Jones. It was my first encounter with FRP. It was an eye-opener.

I'm still trying to figure out the historical graph of FRP efforts (what inspired what, etc.). I've just discovered Frappe, and it seems to be quite similar to [Sodium](https://github.com/SodiumFRP/sodium), the experimental FRP library described in the mentioned book. It has Streams/Signals which are like Stream/Cell in Sodium, the primitive set looks similar too.

Is Frappe fully transactional, like Sodium? Are there other important similarities/differences? Which inspired which, or if neither is the case, would you tell which previous FRP libraries inspired you while creating Frappe?

Also, how does this Frappe relate to [Frappe for Java](https://www.antonycourtney.com/pubs/frappe-padl01.pdf)?

**Comment by wolfiestyle** [comment]
This library is mostly a reimplementation of Carboxyl with different goals and tradeoffs (the api is similar). I dont know much about Sodium so i can't compare it.
And it's not related to Frappe for java, the name is just a coincidence.
